branches:
  only:
  - master
  - develop
language: python
sudo: required
services:
 - docker
python:
  - "3.5" 
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo $TRAVIS_COMMIT  
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - docker build -t fandoghpaas/vote:$TRAVIS_COMMIT ./vote
  - docker build -t fandoghpaas/worker:$TRAVIS_COMMIT ./worker
  - docker build -t fandoghpaas/result:$TRAVIS_COMMIT ./result
  - fandogh service apply -f manifests/postgres-manifest.yml -p VERSION=$TRAVIS_COMMIT || travis_terminate 1;
  - fandogh service apply -f manifests/redis-manifest.yml -p VERSION=$TRAVIS_COMMIT || travis_terminate 1;
  - fandogh service apply -f manifests/result-manifest.yml -p VERSION=$TRAVIS_COMMIT || travis_terminate 1;
  - fandogh service apply -f manifests/vote-manifest.yml -p VERSION=$TRAVIS_COMMIT || travis_terminate 1;
  - fandogh service apply -f manifests/worker-manifest.yml -p VERSION=$TRAVIS_COMMIT || travis_terminate 1;
